- name: Run Postgres container
  docker_container:
    name: postgres
    image: postgres:15-alpine
    env:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
