name: Configure VM

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-a

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: "<public_ip>,"
          options: |
            --private-key ~/.ssh/id_rsa
